version: '3.7'

services:
  magrathea_mongo:
    container_name: "magrathea-mongo"
    image: mongo:latest
    env_file: docker/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ./docker/databases/mongodb:/application

# microservices:
  magrathea_contacs:
    container_name: "magrathea_contacts"
    hostname: api.malte.localhost.com
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: docker/.env
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/api


